%Create parameter structure

% "truncated_normal_rule.m": Copyright 2014 John Burkardt, distributed under the GNU LGPL license.

global params
params = struct('nshocks', 2, ...
'beta', 0.9966,...
'yb', 1,...
'yg', 1.9, ...
'adisutil',1.0, ...
'lambda', 0.0085, ...
'sigma_pi', 0.32, ...
'zeta', 0.5, ...
'eta', 0.5, ...
'kx', 2, ...
'kv', 0.5566, ...
'acobbdoug', 0.6, ...
'epsilon', 1E-4);
